version: "3.8"

services: 
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: 'php artisan serve --host=0.0.0.0'
    ports:
      - 8000:8000
    volumes:
      - ./backend:/app/backend
    depends_on: 
      - db
    networks:
      - app
  

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    tty: true
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/app/frontend
    depends_on:
      - backend
    networks:
      - app

  db:
   image: mysql:8.0.30
   environment:
     MYSQL_DATABASE: "keep_talking_db"
     MYSQL_ROOT_PASSWORD: "root"
   networks:
     - app
   ports:
     - 3307:3306
   expose:
     - 3307

networks:
  app:
    driver: bridge

    